# Generated by Django 3.1.4 on 2020-12-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_Title', models.CharField(max_length=150)),
                ('a_sub_title', models.CharField(max_length=200)),
                ('a_short_description', models.TextField(max_length=600)),
                ('a_feature_1', models.CharField(max_length=250)),
                ('a_feature_2', models.CharField(max_length=250)),
                ('a_feature_3', models.CharField(max_length=250)),
                ('a_anything_else', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='ClientQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=150)),
                ('client_phone', models.IntegerField()),
                ('query_subject', models.CharField(max_length=75)),
                ('client_message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(default='', max_length=150)),
                ('i_phone_number_1', models.IntegerField(default=0)),
                ('i_phone_number_2', models.IntegerField(default=0)),
                ('i_email_address_1', models.EmailField(max_length=254)),
                ('i_email_address_2', models.EmailField(max_length=254)),
                ('i_address_Line_1', models.TextField(max_length=150)),
                ('i_address_Line_2', models.TextField(max_length=150)),
                ('i_motive_speech', models.TextField(max_length=350)),
                ('i_basic_info', models.TextField(max_length=350)),
                ('i_tag_line', models.TextField(max_length=350)),
                ('i_why_chose_us', models.CharField(max_length=150)),
                ('i_whats_app_group_join_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(default='', max_length=150)),
                ('t_image', models.ImageField(default='de_t.png', upload_to='team_photo')),
                ('t_position', models.CharField(max_length=50)),
                ('t_tag_line', models.CharField(max_length=150)),
                ('t_facebook_link', models.CharField(max_length=150)),
                ('t_instagram_link', models.CharField(max_length=150)),
                ('t_whatsapp', models.IntegerField()),
            ],
        ),
    ]
