# Generated by Django 3.1.4 on 2021-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salameng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone1_owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone2_owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
