# Generated by Django 3.1.4 on 2021-01-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salameng', '0002_auto_20210121_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='de_t.png', upload_to='team_photo')),
                ('client_title', models.CharField(max_length=250)),
                ('client_designation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=300)),
                ('Phone1', models.CharField(max_length=11)),
                ('phone2', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='HeroPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_image', models.ImageField(default='de_h_p.png', upload_to='Hero')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='institute',
            name='i_phone_number_1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='institute',
            name='i_phone_number_2',
            field=models.CharField(max_length=11),
        ),
    ]
