# Generated by Django 3.1.4 on 2021-01-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salameng', '0003_auto_20210122_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquery',
            name='client_phone',
            field=models.CharField(max_length=11),
        ),
    ]
