# Generated by Django 3.1.4 on 2021-01-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salameng', '0004_auto_20210122_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('support_hour', models.IntegerField()),
                ('Hard_Workers', models.IntegerField()),
            ],
        ),
    ]
