# Generated by Django 3.1.4 on 2021-01-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salameng', '0005_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numbers',
            old_name='Hard_Workers',
            new_name='hard_Workers',
        ),
    ]
