# Generated by Django 3.1.4 on 2020-12-25 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_category_name', models.CharField(max_length=250)),
                ('ac_category_details', models.TextField(max_length=250)),
                ('ac_category_image', models.ImageField(default='de_ac_cat.png', upload_to='ac_cat_photo')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(max_length=250)),
                ('ac_brand_name', models.CharField(max_length=50)),
                ('ac_model_number', models.CharField(max_length=30)),
                ('ac_image', models.ImageField(default='de_ac.png', upload_to='ac_photo')),
                ('ac_description', models.TextField(max_length=1000, null=True)),
                ('ac_normal_price', models.IntegerField(default=0)),
                ('ac_discounted_price', models.IntegerField(default=0, null=True)),
                ('ac_discount_percent', models.IntegerField(default=0, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('ac_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.accategory')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-upload_date',),
            },
        ),
    ]
