# Generated by Django 3.1.4 on 2021-01-22 05:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_fridgec_fridgecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FridgeC',
            new_name='Fridge',
        ),
    ]
